# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestShowCart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_showCart(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".success:nth-child(1) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".success:nth-child(1) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".success:nth-child(1) > td:nth-child(3)").click()
    self.driver.find_element(By.ID, "totalp").click()
    self.driver.close()



if __name__ == "__main__":
    pytest.main(["-v", "./reports/reportesCart.html"])
