# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForm():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_form(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Juanita")
    self.driver.find_element(By.ID, "country").send_keys("Mexico")
    self.driver.find_element(By.ID, "city").send_keys("Mexico")
    self.driver.find_element(By.ID, "card").send_keys("411111111111111111")
    self.driver.find_element(By.ID, "month").send_keys("12")
    self.driver.find_element(By.ID, "year").send_keys("90")
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "h2:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lead").click()
    self.driver.close()
  


if __name__ == "__main__":
    pytest.main(["-v", "./reports/reporteForm.html"])
